namespace DBWeaver.Ddl.SchemaAnalysis.Domain.Enums;

public enum SchemaRuleCode
{
    FK_CATALOG_INCONSISTENT,
    MISSING_FK,
    NAMING_CONVENTION_VIOLATION,
    LOW_SEMANTIC_NAME,
    MISSING_REQUIRED_COMMENT,
    NF1_HINT_MULTI_VALUED,
    NF2_HINT_PARTIAL_DEPENDENCY,
    NF3_HINT_TRANSITIVE_DEPENDENCY,
}
